tests: explicitly add staged python packages to path (#17521)
Fix [Error executing openstack:ubuntu-26.04-64:tests/main/interfaces-location-control](https://github.com/canonical/snapd/actions/runs/32747636825/job/97529045324?pr=17373#step:25:97)

```
...
retry: command sh -c tests.session -u test exec test-snapd-location-control-provider.consumer Get | MATCH "location-provider-added" failed with code 1
retry: next attempt in 1.0 second(s) (attempt 9 of 10)
Traceback (most recent call last):
File "/snap/test-snapd-location-control-provider/32/consumer", line 3, in <module>
import dbus
ModuleNotFoundError: No module named 'dbus'
grep error: pattern not found, got:

retry: command sh -c tests.session -u test exec test-snapd-location-control-provider.consumer Get | MATCH "location-provider-added" failed with code 1
retry: command sh -c tests.session -u test exec test-snapd-location-control-provider.consumer Get | MATCH "location-provider-added" keeps failing after 10 attempts
```

(cherry picked from commit 8405b95a97a101583c10d0720e5aec7ee22e5b6a)